"""
Django settings for pfootball project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()


environ.Env.read_env(os.path.join(BASE_DIR,'file.env'))



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$q8we!u&p7@8-=&fhepkpr!4nh163hj(&clx9lcl3nrd-cn9dw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ["*"]
ALLOWED_HOSTS = ["postyourfootballcv.com"]
CSRF_TRUSTED_ORIGINS = ["https://postyourfootballcv.com"]



# Application definition
AUTH_USER_MODEL = 'accounts.Account'



# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.import_export",
    "unfold.contrib.guardian",
    "unfold.contrib.simple_history",
    "unfold.contrib.forms",
    "unfold.contrib.inlines",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'phonenumber_field',     # for PhoneNumberField
    'django_countries',      # for CountryField
    'multiselectfield',      # for MultiSelectField
    'pycv',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pfootball.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pfootball.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE':'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),  
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'

# if DEBUG:
STATICFILES_DIRS = [os.path.join(BASE_DIR,'static')]
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# else:
STATIC_ROOT = os.path.join(BASE_DIR,'staticfiles')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.zoho.com'
# EMAIL_PORT = 587
# EMAIL_HOST_USER = env('EMAIL_HOST_USER')
# EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
# DEFAULT_FROM_EMAIL = env('EMAIL_HOST_USER')
# EMAIL_USE_TLS = True
# EMAIL_USE_SSL = False

EMAIL_BACKEND      = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST         = 'smtp.zoho.com'       # or smtp.zoho.com
EMAIL_PORT         = 465
EMAIL_USE_TLS      = False
EMAIL_USE_SSL      = True
EMAIL_HOST_USER    = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD= env('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER






UNFOLD = {
    "SITE_HEADER": "POST YOUR FOOTBALL CV",
    "SITE_TITLE": "POST YOUR FOOTBALL CV Admin",
    "SITE_SUBHEADER": "POST YOUR FOOTBALL CV Admin Panel",
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": lambda request: static("assets/img/logo.png"),
        "dark": lambda request: static("assets/img/logo.png"),
    },
    "SITE_LOGO": {
        "light": lambda request: static("assets/img/logo.png"),
        "dark": lambda request: static("assets/img/logo.png"),
    },
    "STYLES": [
        lambda request: static("css/admin-logo.css"),
    ],
    "DASHBOARD": {
        "show_search": True,
        "show_all_applications": False,
        "cards": [
            {
                "title": _("Users"),
                "icon": "group",
                "link": reverse_lazy("admin:accounts_account_changelist"),
                "description": _("Manage all registered user accounts."),
            },
            {
                "title": _("Job Applications"),
                "icon": "assignment",
                "link": reverse_lazy("admin:accounts_playerjobapplication_changelist"),
                "description": _("Review and process player job applications."),
            },
            {
                "title": _("Verified Players"),
                "icon": "check_circle",
                "link": reverse_lazy("admin:accounts_verifiedplayer_changelist"),
                "description": _("Manage your pool of verified & available players."),
            },
            {
                "title": _("Football Jobs"),
                "icon": "sports_soccer",
                "link": reverse_lazy("admin:accounts_footballjob_changelist"),  # change accounts
                "description": _("Manage football jobs, countries, and requirements."),
            },
        ],
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("User Management"),
                "icon": "account_circle",
                "collapsible": False,
                "items": [
                    {
                        "title": _("All Users"),
                        "icon": "group",
                        "link": reverse_lazy("admin:accounts_account_changelist"),
                    },
                ],
            },
            {
                "title": _("Applications"),
                "icon": "assignment",
                "collapsible": False,
                "items": [
                    {
                        "title": _("Player Applications"),
                        "icon": "description",
                        "link": reverse_lazy("admin:accounts_playerjobapplication_changelist"),
                    },
                ],
            },
            {
                "title": _("Verified Players"),
                "icon": "check_circle",
                "collapsible": False,
                "items": [
                    {
                        "title": _("Player Pool"),
                        "icon": "verified_user",
                        "link": reverse_lazy("admin:accounts_verifiedplayer_changelist"),
                    },
                ],
            },
            {
                "title": _("Football Jobs Management"),
                "icon": "sports_soccer",
                "collapsible": True,
                "items": [
                    {
                        "title": _("Football Jobs"),
                        "icon": "sports",
                        "link": reverse_lazy("admin:accounts_footballjob_changelist"),  # change accounts
                    },
                ],
            },
        ],
    },
}
