# Generated by Django 5.2 on 2025-04-24 11:31

import django_countries.fields
import multiselectfield.db.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerJobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('primary_language', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email_address', models.EmailField(max_length=254)),
                ('home_address', models.TextField()),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters', max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=5, null=True)),
                ('dominant_positions', multiselectfield.db.fields.MultiSelectField(choices=[('GK', 'Goalkeeper'), ('DF', 'Defender'), ('MF', 'Midfielder'), ('FW', 'Forward')], help_text='Select one or more positions', max_length=20)),
                ('current_club', models.CharField(max_length=150)),
                ('current_league', models.CharField(max_length=150)),
                ('coach_name', models.CharField(max_length=150)),
                ('coach_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('coach_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('current_location', models.CharField(max_length=150)),
                ('passport_issuing_country', django_countries.fields.CountryField(max_length=2)),
                ('resume', models.FileField(blank=True, help_text='Upload your CV (PDF/DOCX)', null=True, upload_to='resumes/')),
                ('highlight_video_url', models.URLField(blank=True, help_text='Link to highlight reel', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
