# Generated by Django 5.2 on 2025-04-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_playerjobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_pics/profile_pic.webp', upload_to='profile_pics/'),
        ),
    ]
