# Generated by Django 5.2 on 2025-04-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='birth_date',
            field=models.CharField(blank=True, help_text='e.g january 5th, 1996', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='birth_place',
            field=models.CharField(blank=True, help_text='e.g Manchester - UK', max_length=100, null=True),
        ),
    ]
