# Generated by Django 5.2 on 2025-04-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_country_jobposition_jobrequirement_footballjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballjob',
            name='country',
        ),
        migrations.RemoveField(
            model_name='footballjob',
            name='positions',
        ),
        migrations.RemoveField(
            model_name='footballjob',
            name='requirements',
        ),
        migrations.AddField(
            model_name='footballjob',
            name='country_flag',
            field=models.ImageField(blank=True, null=True, upload_to='country_flags/'),
        ),
        migrations.AddField(
            model_name='footballjob',
            name='country_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footballjob',
            name='position_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footballjob',
            name='requirement_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='JobPosition',
        ),
        migrations.DeleteModel(
            name='JobRequirement',
        ),
    ]
