# Generated by Django 5.2 on 2025-04-28 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_footballjob_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballjob',
            name='apply_link',
        ),
    ]
