# Generated by Django 5.2 on 2025-05-23 12:17

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_resetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballjob',
            name='country_flag',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.get_upload_to),
        ),
    ]
